# Generated by Django 4.2.4 on 2023-08-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassroomFacilty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("facilty_name", models.CharField(max_length=50)),
                ("excellent_rating", models.IntegerField()),
                ("very_good_rating", models.IntegerField()),
                ("good_rating", models.IntegerField()),
                ("fair_rating", models.IntegerField()),
                ("poor_rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ClassSizeFacilty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("facilty_name", models.CharField(max_length=50)),
                ("excellent_rating", models.IntegerField()),
                ("very_good_rating", models.IntegerField()),
                ("good_rating", models.IntegerField()),
                ("fair_rating", models.IntegerField()),
                ("poor_rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TechnologyFacilty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("facilty_name", models.CharField(max_length=50)),
                ("excellent_rating", models.IntegerField()),
                ("very_good_rating", models.IntegerField()),
                ("good_rating", models.IntegerField()),
                ("fair_rating", models.IntegerField()),
                ("poor_rating", models.IntegerField()),
            ],
        ),
    ]
