# Generated by Django 4.2.4 on 2023-08-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FaciltyForm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuatitativeFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("facilty_name", models.CharField(max_length=50)),
                ("student_number", models.CharField(max_length=50)),
                ("registration_number", models.CharField(max_length=50)),
                ("feedback_field", models.CharField(max_length=5000)),
                ("suggestion_field", models.CharField(max_length=5000)),
            ],
        ),
    ]
