# Generated by Django 4.2.4 on 2023-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FaciltyForm", "0002_quatitativefeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="quatitativefeedback",
            name="feedback_sentiment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quatitativefeedback",
            name="suggestion_sentiment",
            field=models.IntegerField(default=0),
        ),
    ]
